name: Publish JAR

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish package
        run: |
          mvn -B deploy:deploy-file \
            -Dfile=./paquete6-1.0.jar \
            -DpomFile=./pom.xml \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/ajuzadolfo/paquetes6jar \
            -Dtoken=${{ secrets.AJUZ_TOKEN }} 
